CFLAGS = -c -g -Wall -std=gnu99 `pkg-config fuse --cflags --libs`

LDFLAGS = `pkg-config fuse --cflags --libs`

# Uncomment on of the following three lines to compile
#SOURCES= disk_emu.c sfs_api.c bitmap.c sfs_test.c sfs_api.h bitmap.h
#SOURCES= disk_emu.c sfs_api.c bitmap.c sfs_test2.c sfs_api.h bitmap.h
SOURCES= disk_emu.c sfs_api.c bitmap.c fuse_wrappers.c sfs_api.h bitmap.h

OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=Felix_Dube_sfs

all: $(SOURCES) $(HEADERS) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	gcc $(OBJECTS) $(LDFLAGS) -o $@

.c.o:
	gcc $(CFLAGS) $< -o $@

clean:
	rm -rf *.o *~ $(EXECUTABLE)
